<a href="https://colab.research.google.com/github/Ravalika-123/AI-ML-PROJECT/blob/main/leaf_disease_detection_svm_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import os
from skimage.transform import resize
from skimage.color import rgb2gray
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix
data_dir = '/content/drive/MyDrive/LEAF DISEASE DATASET'
classes = ['TomatoHealthy', 'TomatoDiseases']
num_classes = len(classes)
img_size = (150,150)
X = []
y = []
for i in range(num_classes):
    path = os.path.join(data_dir, classes[i])
    for img in os.listdir(path):
        try:
            # resize images to a fixed size
            img_array = resize(rgb2gray(plt.imread(os.path.join(path, img))), img_size)
            X.append(img_array)
            y.append(i)
        except Exception as e:
            print(e)


X = np.array(X)
y = np.array(y)

print(X)
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
     

X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)

model = svm.SVC(kernel='linear', C=1.0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
     

acc = accuracy_score(y_test, y_pred)
     

print("Accuracy:", acc)

[[[0.55142781 0.63030218 0.55186323 ... 0.5652069  0.56811253 0.55332319]
  [0.57775428 0.55745389 0.58876906 ... 0.54808441 0.56165276 0.55506312]
  [0.55200262 0.53988999 0.53372851 ... 0.54180439 0.55090845 0.54438085]
  ...
  [0.30701375 0.35475833 0.35349908 ... 0.36242473 0.39762344 0.38987742]
  [0.36021472 0.34557831 0.35412414 ... 0.3840711  0.37205687 0.3624213 ]
  [0.3656218  0.36230492 0.32963738 ... 0.37626941 0.34901778 0.41343947]]

 [[0.53456767 0.47929724 0.4639286  ... 0.53303079 0.56919989 0.48493785]
  [0.5147381  0.46783921 0.478946   ... 0.51019674 0.53016418 0.5020077 ]
  [0.52074335 0.46389092 0.53247664 ... 0.54556256 0.55727316 0.49228024]
  ...
  [0.35819707 0.37622741 0.30212085 ... 0.33415115 0.47048323 0.32782695]
  [0.31472986 0.34854404 0.42018645 ... 0.32699768 0.33853501 0.34774783]
  [0.33497242 0.27419703 0.34940826 ... 0.31903584 0.31676998 0.37258347]]

 [[0.63739581 0.68788675 0.55993265 ... 0.69071823 0.6356024  0.50018537]
  [0.41981867 0.739038

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
