<a href="https://colab.research.google.com/github/Ravalika-123/AI-ML-PROJECT/blob/main/logistic_leaf_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import os
import numpy as np
from skimage.io import imread
import matplotlib.pyplot as plt
from skimage.color import rgb2gray
from skimage.transform import resize
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
     

data_dir = '/content/drive/MyDrive/LEAF DISEASE DATASET'
classes = ['TomatoHealthy', 'TomatoDiseases']
num_classes = len(classes)
img_size = (200,200)

X = []
y = []
for i in range(num_classes):
    path = os.path.join(data_dir, classes[i])
    for img in os.listdir(path):
        try:
            img_array = resize(rgb2gray(plt.imread(os.path.join(path, img))), img_size)
            X.append(img_array)
            y.append(i)
        except Exception as e:
            print(e)


X = np.array(X)
y = np.array(y)

print(X)
print(y)

print(X.shape, y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

     

model = LogisticRegression()
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

model.fit(X_train_flat, y_train)


y_pred = model.predict(X_test_flat)


acc = accuracy_score(y_test, y_pred)

print('Accuracy:', acc)
print('Accuracy Percentage:',round(acc*100,3),"%")

[[[0.53179961 0.61478784 0.61838157 ... 0.56464039 0.56353922 0.54745765]
  [0.57270784 0.56382627 0.58292275 ... 0.5612051  0.56652902 0.55545608]
  [0.60293059 0.54377765 0.56231882 ... 0.54682863 0.55506392 0.54494627]
  ...
  [0.36699176 0.35170549 0.37828588 ... 0.38624353 0.3850749  0.37400824]
  [0.35948118 0.32495255 0.31996431 ... 0.37479255 0.35694314 0.38066706]
  [0.37720353 0.37451176 0.31636431 ... 0.36831412 0.36452902 0.44117059]]

 [[0.56234549 0.50142157 0.49936039 ... 0.59126784 0.54498863 0.47813216]
  [0.51533529 0.46793451 0.44085843 ... 0.52141686 0.51072824 0.48103882]
  [0.52865451 0.46630157 0.42545451 ... 0.50557373 0.52349529 0.51162078]
  ...
  [0.31581255 0.34924784 0.35582039 ... 0.34679098 0.38643804 0.33758314]
  [0.34994902 0.33306275 0.30026745 ... 0.34026549 0.34516588 0.34852118]
  [0.29887922 0.33315686 0.29458902 ... 0.36351255 0.34306235 0.38371961]]

 [[0.57306784 0.72829608 0.60117765 ... 0.70469922 0.51903333 0.46204667]
  [0.54542549 0.666904

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
